In [37]:
import pandas as pd
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect
import numpy as np

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)

sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

In [38]:
# Visualize input data
df_Passenger_Miles_USA = pd.read_excel('../row_data/table_01_40_112323.xlsx',sheet_name='1-40',skiprows=[0])

df_Passenger_Miles_USA

,Unnamed: 0,1960,1965,1970,1975,1980,1985,1990,1991,1992,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"U.S. air carrier, certificated, domestic, all ...",31099,53226,108442,119591.474,190765.929,275863.547,337215.225536,329787.967501,345019.612781,...,579461.449776,597005.003552,632154.824127,661477.927482,685472.464806,722415.333641,754449.995048,304493.678823,573403.814883,708959.674996
2,General aviation,2300,N,9100,N,14700,N,13000,N,N,...,N,N,N,N,N,N,N,N,N,N
3,"Highway, total",1272078.4,1555237.28,2042002.28,2404954.4,2653510.21,2991120.8,3539602.56,3578582.44,3676688.44,...,5083123.464937,5158160.854828,5282710.250066,5411827.622999,5482189.757044,5545845.303523,5579125.972272,4934929.06272,5335751.806042,U
4,"Light duty vehicle, short wheel basea,b",1144673.4,1394803.28,1750897,1954165.5,2011988.76,2094620.64,2281390.92,2200259.7,2208226.09,...,3507723.097311,3502000.690363,3628378.881552,3699794.438008,3709919.196131,3729610.234329,3765896.012144,3225113.80116,3471173.760722,U
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,"1985: Amtrak, Amtrak FY95 Annual Report (Washi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,"1990-2000: Amtrak, Amtrak Annual Report (Washi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,"2001-22: Amtrak, Energy Management Department ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,"Walking, Cycling:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,"U.S. Department of Transportation, Bureau of T...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df_Passenger_Miles_USA['Unnamed: 0'].head(23)

0                                                   Air
1     U.S. air carrier, certificated, domestic, all ...
2                                      General aviation
3                                        Highway, total
4               Light duty vehicle, short wheel basea,b
5                                           Motorcycleb
6                Light duty vehicle, long wheel basea,b
7             Truck, single-unit 2-axle 6-tire or moreb
8                                    Truck, combination
9                                                Busc,e
10                                      Transitd, total
11                                         Motor busc,e
12                                        Commuter buse
13                                          Light railf
14                                           Heavy rail
15                                         Trolley busc
16                                        Commuter rail
17                                   Demand responsec,d
18                                          Ferry boatg
19                                             Otherg,h
20                                    Intercity/Amtraki
21                                             Walkingj
22                                             Cyclingj
Name: Unnamed: 0, dtype: object

In [40]:
mypath=grandparentdir
frac_trns_pkm_dem_private_and_public_vars = sorted([f for f in os.listdir(mypath) if f.startswith('frac_trns_pkm_dem_private_and_public')])
frac_trns_pkm_dem_private_and_public_vars

['frac_trns_pkm_dem_private_and_public_human_powered',
 'frac_trns_pkm_dem_private_and_public_powered_bikes',
 'frac_trns_pkm_dem_private_and_public_public',
 'frac_trns_pkm_dem_private_and_public_road_light',
 'frac_trns_pkm_dem_private_and_public_water_borne']

In [41]:
mypath=grandparentdir
frac_trns_pkm_dem_regional_vars = sorted([f for f in os.listdir(mypath) if f.startswith('frac_trns_pkm_dem_regional')])
frac_trns_pkm_dem_regional_vars

['frac_trns_pkm_dem_regional_aviation',
 'frac_trns_pkm_dem_regional_rail_passenger',
 'frac_trns_pkm_dem_regional_road_heavy_regional',
 'frac_trns_pkm_dem_regional_road_light',
 'frac_trns_pkm_dem_regional_water_borne']

In [42]:
df_Passenger_Miles_USA['Transport']=df_Passenger_Miles_USA['Unnamed: 0']

years_hist = range(2011,2021+1)

year_data = []

for year in years_hist:

    # Private and Public data

    # Road light
    
    road_light_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Light duty vehicle, short wheel basea,b'][year].values[0]

    # Powered bikes
    
    powered_bikes_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Motorcycleb'][year].values[0]

    # Public

    public_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Busc,e'][year].values[0]

    # For walking and cycling 2017 data will be used for historical data

    walking_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Walkingj'][2017].values[0]
    
    cycling_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Cyclingj'][2017].values[0]

    human_powered_data = walking_data+cycling_data


    # Regional data

    #Aviation

    aviation_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='U.S. air carrier, certificated, domestic, all services'][year].values[0]

    # Rail includes light and heavy
    
    light_rail_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Light railf'][year].values[0]
    
    heavy_rail_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Heavy rail'][year].values[0]

    rail_data = light_rail_data + heavy_rail_data

    # Water borne

    ferry_boat_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Ferry boatg'][year].values[0]

    # Road Heavy

    motor_bus_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Motor busc,e'][year].values[0]

    commuter_bus_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Commuter buse'][year].values[0]

    road_heavy_data = public_data + motor_bus_data + commuter_bus_data

    year_data.append([year,
                      road_light_data,
                     powered_bikes_data,
                      public_data,
                      human_powered_data,
                      aviation_data,
                      rail_data,
                      road_heavy_data,
                      ferry_boat_data
                     ])

    

df_Passenger_Miles_USA_clean = pd.DataFrame(year_data,columns = ['Year', 
                                                                 'road_light_data',
                                                                 'powered_bikes_data',
                                                                 'public_data',
                                                                 'human_powered_data',
                                                                 'aviation_data',
                                                                 'rail_data',
                                                                 'road_heavy_data',
                                                                 'ferry_boat_data'])

df_Passenger_Miles_USA_clean['Total_private_and_public'] = df_Passenger_Miles_USA_clean[[
                                                                 'road_light_data',
                                                                 'powered_bikes_data',
                                                                 'public_data',
                                                                 'human_powered_data',
                                                                 'ferry_boat_data']].sum(axis=1)

df_Passenger_Miles_USA_clean['Total_regional'] = df_Passenger_Miles_USA_clean[[
                                                                 'road_light_data',
                                                                 'aviation_data',
                                                                 'rail_data',
                                                                 'road_heavy_data',
                                                                 'ferry_boat_data']].sum(axis=1)
df_Passenger_Miles_USA_clean

,Year,road_light_data,powered_bikes_data,public_data,human_powered_data,aviation_data,rail_data,road_heavy_data,ferry_boat_data,Total_private_and_public,Total_regional
0,2011,3.464405e+06,21516.752486,271150.553914,42150,565613.645358,19680.043970,291709.129349,389.384191,3.799612e+06,4.341797e+06
1,2012,3.490438e+06,24815.916144,291201.842465,42150,570438.230553,20005.280768,312344.034905,402.115701,3.849008e+06,4.393628e+06
2,2013,3.507723e+06,23633.293571,299273.239934,42150,579461.449776,20569.252694,320530.642918,402.305934,3.873182e+06,4.428687e+06
3,2014,3.502001e+06,23173.173385,316726.320301,42150,597005.003552,21013.569396,338155.268344,414.209460,3.884464e+06,4.458589e+06
4,2015,3.628379e+06,22751.532129,322962.555934,42150,632154.824127,20961.126411,343055.716617,450.526502,4.016693e+06,4.625001e+06
5,2016,3.699794e+06,23725.111955,325179.647924,42150,661477.927482,21112.485660,345590.655134,489.356333,4.091339e+06,4.728465e+06
6,2017,3.709919e+06,23381.622003,344992.912682,42150,685472.464806,20367.095698,364216.435568,486.037496,4.120930e+06,4.780461e+06
7,2018,3.729610e+06,23296.768568,368430.102665,42150,722415.333641,19642.578370,387054.688208,519.783858,4.164007e+06,4.859243e+06
8,2019,3.765896e+06,22846.373475,361844.289415,42150,754449.995048,20058.485073,380211.422917,546.569597,4.193283e+06,4.921162e+06
9,2020,3.225114e+06,21617.631727,305419.503455,42150,304493.678823,10781.491069,318035.567579,411.191959,3.594712e+06,3.858836e+06
10,2021,3.471174e+06,23658.519408,345697.344871,42150,573403.814883,8445.775428,354446.028005,268.017949,3.882948e+06,4.407737e+06

In [43]:
df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_human_powered'] = df_Passenger_Miles_USA_clean['human_powered_data']/df_Passenger_Miles_USA_clean['Total_private_and_public']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_powered_bikes'] = df_Passenger_Miles_USA_clean['powered_bikes_data']/df_Passenger_Miles_USA_clean['Total_private_and_public']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_public'] = df_Passenger_Miles_USA_clean['public_data']/df_Passenger_Miles_USA_clean['Total_private_and_public']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_road_light'] = df_Passenger_Miles_USA_clean['road_light_data']/df_Passenger_Miles_USA_clean['Total_private_and_public']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_water_borne'] = df_Passenger_Miles_USA_clean['ferry_boat_data']/df_Passenger_Miles_USA_clean['Total_private_and_public']


df_Passenger_Miles_USA_clean

,Year,road_light_data,powered_bikes_data,public_data,human_powered_data,aviation_data,rail_data,road_heavy_data,ferry_boat_data,Total_private_and_public,Total_regional,frac_trns_pkm_dem_private_and_public_human_powered,frac_trns_pkm_dem_private_and_public_powered_bikes,frac_trns_pkm_dem_private_and_public_public,frac_trns_pkm_dem_private_and_public_road_light,frac_trns_pkm_dem_private_and_public_water_borne
0,2011,3.464405e+06,21516.752486,271150.553914,42150,565613.645358,19680.043970,291709.129349,389.384191,3.799612e+06,4.341797e+06,0.011093,0.005663,0.071363,0.911779,0.000102
1,2012,3.490438e+06,24815.916144,291201.842465,42150,570438.230553,20005.280768,312344.034905,402.115701,3.849008e+06,4.393628e+06,0.010951,0.006447,0.075656,0.906841,0.000104
2,2013,3.507723e+06,23633.293571,299273.239934,42150,579461.449776,20569.252694,320530.642918,402.305934,3.873182e+06,4.428687e+06,0.010883,0.006102,0.077268,0.905644,0.000104
3,2014,3.502001e+06,23173.173385,316726.320301,42150,597005.003552,21013.569396,338155.268344,414.209460,3.884464e+06,4.458589e+06,0.010851,0.005966,0.081537,0.901540,0.000107
4,2015,3.628379e+06,22751.532129,322962.555934,42150,632154.824127,20961.126411,343055.716617,450.526502,4.016693e+06,4.625001e+06,0.010494,0.005664,0.080405,0.903325,0.000112
5,2016,3.699794e+06,23725.111955,325179.647924,42150,661477.927482,21112.485660,345590.655134,489.356333,4.091339e+06,4.728465e+06,0.010302,0.005799,0.079480,0.904299,0.000120
6,2017,3.709919e+06,23381.622003,344992.912682,42150,685472.464806,20367.095698,364216.435568,486.037496,4.120930e+06,4.780461e+06,0.010228,0.005674,0.083717,0.900263,0.000118
7,2018,3.729610e+06,23296.768568,368430.102665,42150,722415.333641,19642.578370,387054.688208,519.783858,4.164007e+06,4.859243e+06,0.010122,0.005595,0.088480,0.895678,0.000125
8,2019,3.765896e+06,22846.373475,361844.289415,42150,754449.995048,20058.485073,380211.422917,546.569597,4.193283e+06,4.921162e+06,0.010052,0.005448,0.086291,0.898078,0.000130
9,2020,3.225114e+06,21617.631727,305419.503455,42150,304493.678823,10781.491069,318035.567579,411.191959,3.594712e+06,3.858836e+06,0.011726,0.006014,0.084964,0.897183,0.000114
10,2021,3.471174e+06,23658.519408,345697.344871,42150,573403.814883,8445.775428,354446.028005,268.017949,3.882948e+06,4.407737e+06,0.010855,0.006093,0.089030,0.893953,0.000069

In [44]:
df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_aviation'] = df_Passenger_Miles_USA_clean['aviation_data']/df_Passenger_Miles_USA_clean['Total_regional']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_rail_passenger'] = df_Passenger_Miles_USA_clean['rail_data']/df_Passenger_Miles_USA_clean['Total_regional']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_road_heavy_regional'] = df_Passenger_Miles_USA_clean['road_heavy_data']/df_Passenger_Miles_USA_clean['Total_regional']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_road_light'] = df_Passenger_Miles_USA_clean['road_light_data']/df_Passenger_Miles_USA_clean['Total_regional']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_water_borne'] = df_Passenger_Miles_USA_clean['ferry_boat_data']/df_Passenger_Miles_USA_clean['Total_regional']


df_Passenger_Miles_USA_clean

,Year,road_light_data,powered_bikes_data,public_data,human_powered_data,aviation_data,rail_data,road_heavy_data,ferry_boat_data,Total_private_and_public,...,frac_trns_pkm_dem_private_and_public_human_powered,frac_trns_pkm_dem_private_and_public_powered_bikes,frac_trns_pkm_dem_private_and_public_public,frac_trns_pkm_dem_private_and_public_road_light,frac_trns_pkm_dem_private_and_public_water_borne,frac_trns_pkm_dem_regional_aviation,frac_trns_pkm_dem_regional_rail_passenger,frac_trns_pkm_dem_regional_road_heavy_regional,frac_trns_pkm_dem_regional_road_light,frac_trns_pkm_dem_regional_water_borne
0,2011,3.464405e+06,21516.752486,271150.553914,42150,565613.645358,19680.043970,291709.129349,389.384191,3.799612e+06,...,0.011093,0.005663,0.071363,0.911779,0.000102,0.130272,0.004533,0.067186,0.797920,0.000090
1,2012,3.490438e+06,24815.916144,291201.842465,42150,570438.230553,20005.280768,312344.034905,402.115701,3.849008e+06,...,0.010951,0.006447,0.075656,0.906841,0.000104,0.129833,0.004553,0.071090,0.794432,0.000092
2,2013,3.507723e+06,23633.293571,299273.239934,42150,579461.449776,20569.252694,320530.642918,402.305934,3.873182e+06,...,0.010883,0.006102,0.077268,0.905644,0.000104,0.130843,0.004645,0.072376,0.792046,0.000091
3,2014,3.502001e+06,23173.173385,316726.320301,42150,597005.003552,21013.569396,338155.268344,414.209460,3.884464e+06,...,0.010851,0.005966,0.081537,0.901540,0.000107,0.133900,0.004713,0.075844,0.785450,0.000093
4,2015,3.628379e+06,22751.532129,322962.555934,42150,632154.824127,20961.126411,343055.716617,450.526502,4.016693e+06,...,0.010494,0.005664,0.080405,0.903325,0.000112,0.136682,0.004532,0.074174,0.784514,0.000097
5,2016,3.699794e+06,23725.111955,325179.647924,42150,661477.927482,21112.485660,345590.655134,489.356333,4.091339e+06,...,0.010302,0.005799,0.079480,0.904299,0.000120,0.139893,0.004465,0.073087,0.782452,0.000103
6,2017,3.709919e+06,23381.622003,344992.912682,42150,685472.464806,20367.095698,364216.435568,486.037496,4.120930e+06,...,0.010228,0.005674,0.083717,0.900263,0.000118,0.143390,0.004260,0.076189,0.776059,0.000102
7,2018,3.729610e+06,23296.768568,368430.102665,42150,722415.333641,19642.578370,387054.688208,519.783858,4.164007e+06,...,0.010122,0.005595,0.088480,0.895678,0.000125,0.148668,0.004042,0.079653,0.767529,0.000107
8,2019,3.765896e+06,22846.373475,361844.289415,42150,754449.995048,20058.485073,380211.422917,546.569597,4.193283e+06,...,0.010052,0.005448,0.086291,0.898078,0.000130,0.153307,0.004076,0.077260,0.765245,0.000111
9,2020,3.225114e+06,21617.631727,305419.503455,42150,304493.678823,10781.491069,318035.567579,411.191959,3.594712e+06,...,0.011726,0.006014,0.084964,0.897183,0.000114,0.078908,0.002794,0.082417,0.835774,0.000107
10,2021,3.471174e+06,23658.519408,345697.344871,42150,573403.814883,8445.775428,354446.028005,268.017949,3.882948e+06,...,0.010855,0.006093,0.089030,0.893953,0.000069,0.130090,0.001916,0.080415,0.787518,0.000061

In [45]:
# The similarity of the obtained fractions with the information in https://www.bts.gov/sites/bts.dot.gov/files/states2020/Louisiana.pdf
# in the 'HOW RESIDENTS GET TO WORK' graph allow us to believe that the fractions of passenger per Km (private and pblic) is similar to the National numbers. 

years_proj = range(max(years_hist)+1,2050+1)


for var in frac_trns_pkm_dem_private_and_public_vars:
    
    df_historical = df_Passenger_Miles_USA_clean[['Year',var]].copy()
    df_historical['iso_code3'] = 'LA'
    df_historical['Region'] = 'louisiana'
    df_historical.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/historical/'+var+'.csv')

    # Projected value will be tha same as the last historical value

    year_val = []
    
    for year in years_proj:

        val = df_historical.loc[df_historical['Year']==max(years_hist)][var].values[0]

        year_val.append(['LA','louisiana',year,val])
        
    df_projected_out = pd.DataFrame(year_val, columns=['iso_code3','Region', 'Year',var])

    df_projected_out.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/projected/'+var+'.csv')
    
    print('Ready: ', var)

Ready:  frac_trns_pkm_dem_private_and_public_human_powered
Ready:  frac_trns_pkm_dem_private_and_public_powered_bikes
Ready:  frac_trns_pkm_dem_private_and_public_public
Ready:  frac_trns_pkm_dem_private_and_public_road_light
Ready:  frac_trns_pkm_dem_private_and_public_water_borne

In [46]:
# Regional fractions will be taken a as the national fractions

years_proj = range(max(years_hist)+1,2050+1)


for var in frac_trns_pkm_dem_regional_vars:
    
    df_historical = df_Passenger_Miles_USA_clean[['Year',var]].copy()
    df_historical['iso_code3'] = 'LA'
    df_historical['Region'] = 'louisiana'
    df_historical.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/historical/'+var+'.csv')

    # Projected value will be tha same as the last historical value

    year_val = []
    
    for year in years_proj:

        val = df_historical.loc[df_historical['Year']==max(years_hist)][var].values[0]

        year_val.append(['LA','louisiana',year,val])
        
    df_projected_out = pd.DataFrame(year_val, columns=['iso_code3','Region', 'Year',var])

    df_projected_out.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/projected/'+var+'.csv')
    
    print('Ready: ', var)

Ready:  frac_trns_pkm_dem_regional_aviation
Ready:  frac_trns_pkm_dem_regional_rail_passenger
Ready:  frac_trns_pkm_dem_regional_road_heavy_regional
Ready:  frac_trns_pkm_dem_regional_road_light
Ready:  frac_trns_pkm_dem_regional_water_borne

In [47]:
# Check that values add 1

for year in years_hist:
    val = 0
    for var_name in frac_trns_pkm_dem_regional_vars:
        df_historical = df_Passenger_Miles_USA_clean[['Year',var_name]].copy()
        val += df_historical.loc[df_historical['Year']==year][var_name].values[0]
    print(val)

1.0
1.0
1.0
1.0000000000000002
1.0
1.0
1.0
1.0
0.9999999999999999
0.9999999999999999
0.9999999999999999

In [48]:
# Check that values add 1

for year in years_hist:
    val = 0
    for var_name in frac_trns_pkm_dem_private_and_public_vars:
        df_historical = df_Passenger_Miles_USA_clean[['Year',var_name]].copy()
        val += df_historical.loc[df_historical['Year']==year][var_name].values[0]
    print(val)

1.0
1.0
1.0
1.0
1.0
0.9999999999999999
1.0
1.0
1.0
1.0
1.0