In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

# var_name=os.path.basename(parentdir)

# var_name
import pandas as pd
import numpy as np

df_countries=pd.read_csv("../row_data/Countries_ISO3.csv")
df_countries

                    Country Name ISO3
0                          Aruba  ABW
1    Africa Eastern and Southern  AFE
2                    Afghanistan  AFG
3     Africa Western and Central  AFW
4                         Angola  AGO
..                           ...  ...
261                       Kosovo  XKX
262                  Yemen, Rep.  YEM
263                 South Africa  ZAF
264                       Zambia  ZMB
265                     Zimbabwe  ZWE

[266 rows x 2 columns]

In [2]:
mypath=grandparentdir
frac_trns_pkm_dem_private_vars = sorted([f for f in os.listdir(mypath) if f.startswith('frac_trns_pkm_dem_private')])
frac_trns_pkm_dem_private_vars

['frac_trns_pkm_dem_private_and_public_human_powered',
 'frac_trns_pkm_dem_private_and_public_powered_bikes',
 'frac_trns_pkm_dem_private_and_public_public',
 'frac_trns_pkm_dem_private_and_public_road_light']

In [3]:
frac_trns_pkm_dem_regional_vars = sorted([f for f in os.listdir(mypath) if f.startswith('frac_trns_pkm_dem_r')])
frac_trns_pkm_dem_regional_vars

['frac_trns_pkm_dem_regional_aviation',
 'frac_trns_pkm_dem_regional_rail_passenger',
 'frac_trns_pkm_dem_regional_road_heavy_regional',
 'frac_trns_pkm_dem_regional_road_light']

In [5]:
# Histocical
countries=df_countries['Country Name'].unique()
years_hist=np.arange(2010,2022)

for var_name in frac_trns_pkm_dem_private_vars:
    count_year_dato=[]
    
    for c in countries:
        iso3 = df_countries.loc[df_countries['Country Name']==c]['ISO3'].values[0]
        for y in years_hist:
            if var_name.endswith('human_powered'):
                dato=0.03
            if var_name.endswith('public'):
                dato=0.43
            if var_name.endswith('bikes'):
                dato=0.08
            if var_name.endswith('light'):
                dato=0.46
                
            count_year_dato.append([c,iso3,y,dato])
            
    df_historical_out = pd.DataFrame(count_year_dato, columns=['Nation','iso_code3', 'Year',var_name])
    
    df_historical_out.to_csv(grandparentdir+'/'+var_name+'/input_to_sisepuede/historical/'+var_name+'.csv')
    
    
    
for var_name in frac_trns_pkm_dem_regional_vars:
    count_year_dato=[]
    
    for c in countries:
        iso3 = df_countries.loc[df_countries['Country Name']==c]['ISO3'].values[0]
        for y in years_hist:
            if var_name.endswith('passenger'):
                dato=0.07
            if var_name.endswith('regional'):
                dato=0.3
            if var_name.endswith('aviation'):
                dato=0.33
            if var_name.endswith('light'):
                dato=0.3
                
            count_year_dato.append([c,iso3,y,dato])
            
    df_historical_out = pd.DataFrame(count_year_dato, columns=['Nation','iso_code3', 'Year',var_name])
    
    df_historical_out.to_csv(grandparentdir+'/'+var_name+'/input_to_sisepuede/historical/'+var_name+'.csv')
                
# Projected

# years_proj=np.arange(2022,2051)

start_year = 2022
end_year = 2050

# Create an array of years from start_year to end_year
years = np.arange(start_year, end_year + 1)

for var_name in frac_trns_pkm_dem_private_vars:
    count_year_dato=[]
    
    for c in countries:
        iso3 = df_countries.loc[df_countries['Country Name']==c]['ISO3'].values[0]
        for (i,y) in enumerate(years):
            if var_name.endswith('human_powered'):
                dato=0.03
            if var_name.endswith('public'):
                start_value = 0.43
                end_value = 0.22
                # Perform linear interpolation
                mapped_values = np.interp(years, [start_year, end_year], [start_value, end_value])
                dato=mapped_values[i]
            if var_name.endswith('bikes'):
                start_value = 0.08
                end_value = 0.05
                # Perform linear interpolation
                mapped_values = np.interp(years, [start_year, end_year], [start_value, end_value])
                dato=mapped_values[i]
            if var_name.endswith('light'):
                start_value = 0.46
                end_value = 0.70
                # Perform linear interpolation
                mapped_values = np.interp(years, [start_year, end_year], [start_value, end_value])
                dato=mapped_values[i]
                
            count_year_dato.append([c,iso3,y,dato])
            
    df_projected_out = pd.DataFrame(count_year_dato, columns=['Nation','iso_code3', 'Year',var_name])
    
    df_projected_out.to_csv(grandparentdir+'/'+var_name+'/input_to_sisepuede/projected/'+var_name+'.csv')
    
    
    
for var_name in frac_trns_pkm_dem_regional_vars:
    count_year_dato=[]
    
    for c in countries:
        iso3 = df_countries.loc[df_countries['Country Name']==c]['ISO3'].values[0]
        for (i,y) in enumerate(years):
            if var_name.endswith('passenger'):
                dato=0.07
            if var_name.endswith('regional'):
                start_value = 0.3
                end_value = 0.2
                # Perform linear interpolation
                mapped_values = np.interp(years, [start_year, end_year], [start_value, end_value])
                dato=mapped_values[i]
            if var_name.endswith('aviation'):
                dato=0.33
            if var_name.endswith('light'):
                start_value = 0.3
                end_value = 0.4
                # Perform linear interpolation
                mapped_values = np.interp(years, [start_year, end_year], [start_value, end_value])
                dato=mapped_values[i]
                
            count_year_dato.append([c,iso3,y,dato])
            
    df_projected_out = pd.DataFrame(count_year_dato, columns=['Nation','iso_code3', 'Year',var_name])
    
    df_projected_out.to_csv(grandparentdir+'/'+var_name+'/input_to_sisepuede/projected/'+var_name+'.csv')