In [10]:
import pandas as pd
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect
import numpy as np

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)

sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

In [2]:
# Visualize input data
df_Passenger_Miles_USA = pd.read_excel('../row_data/table_01_40_112323.xlsx',sheet_name='1-40',skiprows=[0])

df_Passenger_Miles_USA

,Unnamed: 0,1960,1965,1970,1975,1980,1985,1990,1991,1992,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"U.S. air carrier, certificated, domestic, all ...",31099,53226,108442,119591.474,190765.929,275863.547,337215.225536,329787.967501,345019.612781,...,579461.449776,597005.003552,632154.824127,661477.927482,685472.464806,722415.333641,754449.995048,304493.678823,573403.814883,708959.674996
2,General aviation,2300,N,9100,N,14700,N,13000,N,N,...,N,N,N,N,N,N,N,N,N,N
3,"Highway, total",1272078.4,1555237.28,2042002.28,2404954.4,2653510.21,2991120.8,3539602.56,3578582.44,3676688.44,...,5083123.464937,5158160.854828,5282710.250066,5411827.622999,5482189.757044,5545845.303523,5579125.972272,4934929.06272,5335751.806042,U
4,"Light duty vehicle, short wheel basea,b",1144673.4,1394803.28,1750897,1954165.5,2011988.76,2094620.64,2281390.92,2200259.7,2208226.09,...,3507723.097311,3502000.690363,3628378.881552,3699794.438008,3709919.196131,3729610.234329,3765896.012144,3225113.80116,3471173.760722,U
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,"1985: Amtrak, Amtrak FY95 Annual Report (Washi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,"1990-2000: Amtrak, Amtrak Annual Report (Washi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,"2001-22: Amtrak, Energy Management Department ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,"Walking, Cycling:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,"U.S. Department of Transportation, Bureau of T...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_Passenger_Miles_USA['Unnamed: 0'].head(23)

0                                                   Air
1     U.S. air carrier, certificated, domestic, all ...
2                                      General aviation
3                                        Highway, total
4               Light duty vehicle, short wheel basea,b
5                                           Motorcycleb
6                Light duty vehicle, long wheel basea,b
7             Truck, single-unit 2-axle 6-tire or moreb
8                                    Truck, combination
9                                                Busc,e
10                                      Transitd, total
11                                         Motor busc,e
12                                        Commuter buse
13                                          Light railf
14                                           Heavy rail
15                                         Trolley busc
16                                        Commuter rail
17                                   Demand responsec,d
18                                          Ferry boatg
19                                             Otherg,h
20                                    Intercity/Amtraki
21                                             Walkingj
22                                             Cyclingj
Name: Unnamed: 0, dtype: object

In [13]:
mypath=grandparentdir
frac_trns_pkm_dem_private_and_public_vars = sorted([f for f in os.listdir(mypath) if f.startswith('frac_trns_pkm_dem_private_and_public')])
frac_trns_pkm_dem_private_and_public_vars

['frac_trns_pkm_dem_private_and_public_human_powered',
 'frac_trns_pkm_dem_private_and_public_powered_bikes',
 'frac_trns_pkm_dem_private_and_public_public',
 'frac_trns_pkm_dem_private_and_public_road_light']

In [14]:
mypath=grandparentdir
frac_trns_pkm_dem_regional_vars = sorted([f for f in os.listdir(mypath) if f.startswith('frac_trns_pkm_dem_regional')])
frac_trns_pkm_dem_regional_vars

['frac_trns_pkm_dem_regional_aviation',
 'frac_trns_pkm_dem_regional_rail_passenger',
 'frac_trns_pkm_dem_regional_road_heavy_regional',
 'frac_trns_pkm_dem_regional_road_light']

In [27]:
df_Passenger_Miles_USA['Transport']=df_Passenger_Miles_USA['Unnamed: 0']

years_hist = range(2011,2021+1)

year_data = []

for year in years_hist:

    # Private and Public data

    # Road light
    
    road_light_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Light duty vehicle, short wheel basea,b'][year].values[0]

    # Powered bikes
    
    powered_bikes_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Motorcycleb'][year].values[0]

    # Public

    public_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Busc,e'][year].values[0]

    # For walking and cycling 2017 data will be used for historical data

    walking_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Walkingj'][2017].values[0]
    
    cycling_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Cyclingj'][2017].values[0]

    human_powered_data = walking_data+cycling_data


    # Regional data

    #Aviation

    aviation_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='U.S. air carrier, certificated, domestic, all services'][year].values[0]

    # Rail includes light and heavy
    
    light_rail_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Light railf'][year].values[0]
    
    heavy_rail_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Heavy rail'][year].values[0]

    rail_data = light_rail_data + heavy_rail_data

    # Water borne

    ferry_boat_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Ferry boatg'][year].values[0]

    # Road Heavy

    motor_bus_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Motor busc,e'][year].values[0]

    commuter_bus_data = df_Passenger_Miles_USA[df_Passenger_Miles_USA['Unnamed: 0']=='Commuter buse'][year].values[0]

    road_heavy_data = public_data + motor_bus_data + commuter_bus_data

    year_data.append([year,
                      road_light_data,
                     powered_bikes_data,
                      public_data,
                      human_powered_data,
                      aviation_data,
                      rail_data,
                      road_heavy_data,
                      ferry_boat_data
                     ])

    

df_Passenger_Miles_USA_clean = pd.DataFrame(year_data,columns = ['Year', 
                                                                 'road_light_data',
                                                                 'powered_bikes_data',
                                                                 'public_data',
                                                                 'human_powered_data',
                                                                 'aviation_data',
                                                                 'rail_data',
                                                                 'road_heavy_data',
                                                                 'ferry_boat_data'])

df_Passenger_Miles_USA_clean['Total'] = df_Passenger_Miles_USA_clean[['road_light_data',
                                                                 'powered_bikes_data',
                                                                 'public_data',
                                                                 'human_powered_data',
                                                                 'aviation_data',
                                                                 'rail_data',
                                                                 'road_heavy_data',
                                                                 'ferry_boat_data']].sum(axis=1)
df_Passenger_Miles_USA_clean

,Year,road_light_data,powered_bikes_data,public_data,human_powered_data,aviation_data,rail_data,road_heavy_data,ferry_boat_data,Total
0,2011,3.464405e+06,21516.752486,271150.553914,42150,565613.645358,19680.043970,291709.129349,389.384191,4.676615e+06
1,2012,3.490438e+06,24815.916144,291201.842465,42150,570438.230553,20005.280768,312344.034905,402.115701,4.751796e+06
2,2013,3.507723e+06,23633.293571,299273.239934,42150,579461.449776,20569.252694,320530.642918,402.305934,4.793743e+06
3,2014,3.502001e+06,23173.173385,316726.320301,42150,597005.003552,21013.569396,338155.268344,414.209460,4.840638e+06
4,2015,3.628379e+06,22751.532129,322962.555934,42150,632154.824127,20961.126411,343055.716617,450.526502,5.012865e+06
5,2016,3.699794e+06,23725.111955,325179.647924,42150,661477.927482,21112.485660,345590.655134,489.356333,5.119520e+06
6,2017,3.709919e+06,23381.622003,344992.912682,42150,685472.464806,20367.095698,364216.435568,486.037496,5.190986e+06
7,2018,3.729610e+06,23296.768568,368430.102665,42150,722415.333641,19642.578370,387054.688208,519.783858,5.293119e+06
8,2019,3.765896e+06,22846.373475,361844.289415,42150,754449.995048,20058.485073,380211.422917,546.569597,5.348003e+06
9,2020,3.225114e+06,21617.631727,305419.503455,42150,304493.678823,10781.491069,318035.567579,411.191959,4.228023e+06
10,2021,3.471174e+06,23658.519408,345697.344871,42150,573403.814883,8445.775428,354446.028005,268.017949,4.819243e+06

In [28]:
df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_human_powered'] = df_Passenger_Miles_USA_clean['human_powered_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_powered_bikes'] = df_Passenger_Miles_USA_clean['powered_bikes_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_public'] = df_Passenger_Miles_USA_clean['public_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_private_and_public_road_light'] = df_Passenger_Miles_USA_clean['road_light_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean

,Year,road_light_data,powered_bikes_data,public_data,human_powered_data,aviation_data,rail_data,road_heavy_data,ferry_boat_data,Total,frac_trns_pkm_dem_private_and_public_human_powered,frac_trns_pkm_dem_private_and_public_powered_bikes,frac_trns_pkm_dem_private_and_public_public,frac_trns_pkm_dem_private_and_public_road_light
0,2011,3.464405e+06,21516.752486,271150.553914,42150,565613.645358,19680.043970,291709.129349,389.384191,4.676615e+06,0.009013,0.004601,0.057980,0.740793
1,2012,3.490438e+06,24815.916144,291201.842465,42150,570438.230553,20005.280768,312344.034905,402.115701,4.751796e+06,0.008870,0.005222,0.061282,0.734551
2,2013,3.507723e+06,23633.293571,299273.239934,42150,579461.449776,20569.252694,320530.642918,402.305934,4.793743e+06,0.008793,0.004930,0.062430,0.731729
3,2014,3.502001e+06,23173.173385,316726.320301,42150,597005.003552,21013.569396,338155.268344,414.209460,4.840638e+06,0.008708,0.004787,0.065431,0.723458
4,2015,3.628379e+06,22751.532129,322962.555934,42150,632154.824127,20961.126411,343055.716617,450.526502,5.012865e+06,0.008408,0.004539,0.064427,0.723813
5,2016,3.699794e+06,23725.111955,325179.647924,42150,661477.927482,21112.485660,345590.655134,489.356333,5.119520e+06,0.008233,0.004634,0.063518,0.722684
6,2017,3.709919e+06,23381.622003,344992.912682,42150,685472.464806,20367.095698,364216.435568,486.037496,5.190986e+06,0.008120,0.004504,0.066460,0.714685
7,2018,3.729610e+06,23296.768568,368430.102665,42150,722415.333641,19642.578370,387054.688208,519.783858,5.293119e+06,0.007963,0.004401,0.069605,0.704615
8,2019,3.765896e+06,22846.373475,361844.289415,42150,754449.995048,20058.485073,380211.422917,546.569597,5.348003e+06,0.007881,0.004272,0.067660,0.704169
9,2020,3.225114e+06,21617.631727,305419.503455,42150,304493.678823,10781.491069,318035.567579,411.191959,4.228023e+06,0.009969,0.005113,0.072237,0.762795
10,2021,3.471174e+06,23658.519408,345697.344871,42150,573403.814883,8445.775428,354446.028005,268.017949,4.819243e+06,0.008746,0.004909,0.071733,0.720274

In [29]:
df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_aviation'] = df_Passenger_Miles_USA_clean['aviation_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_rail_passenger'] = df_Passenger_Miles_USA_clean['rail_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_road_heavy_regional'] = df_Passenger_Miles_USA_clean['road_heavy_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean['frac_trns_pkm_dem_regional_road_light'] = df_Passenger_Miles_USA_clean['road_light_data']/df_Passenger_Miles_USA_clean['Total']

df_Passenger_Miles_USA_clean

,Year,road_light_data,powered_bikes_data,public_data,human_powered_data,aviation_data,rail_data,road_heavy_data,ferry_boat_data,Total,frac_trns_pkm_dem_private_and_public_human_powered,frac_trns_pkm_dem_private_and_public_powered_bikes,frac_trns_pkm_dem_private_and_public_public,frac_trns_pkm_dem_private_and_public_road_light,frac_trns_pkm_dem_regional_aviation,frac_trns_pkm_dem_regional_rail_passenger,frac_trns_pkm_dem_regional_road_heavy_regional,frac_trns_pkm_dem_regional_road_light
0,2011,3.464405e+06,21516.752486,271150.553914,42150,565613.645358,19680.043970,291709.129349,389.384191,4.676615e+06,0.009013,0.004601,0.057980,0.740793,0.120945,0.004208,0.062376,0.740793
1,2012,3.490438e+06,24815.916144,291201.842465,42150,570438.230553,20005.280768,312344.034905,402.115701,4.751796e+06,0.008870,0.005222,0.061282,0.734551,0.120047,0.004210,0.065732,0.734551
2,2013,3.507723e+06,23633.293571,299273.239934,42150,579461.449776,20569.252694,320530.642918,402.305934,4.793743e+06,0.008793,0.004930,0.062430,0.731729,0.120879,0.004291,0.066864,0.731729
3,2014,3.502001e+06,23173.173385,316726.320301,42150,597005.003552,21013.569396,338155.268344,414.209460,4.840638e+06,0.008708,0.004787,0.065431,0.723458,0.123332,0.004341,0.069858,0.723458
4,2015,3.628379e+06,22751.532129,322962.555934,42150,632154.824127,20961.126411,343055.716617,450.526502,5.012865e+06,0.008408,0.004539,0.064427,0.723813,0.126106,0.004181,0.068435,0.723813
5,2016,3.699794e+06,23725.111955,325179.647924,42150,661477.927482,21112.485660,345590.655134,489.356333,5.119520e+06,0.008233,0.004634,0.063518,0.722684,0.129207,0.004124,0.067505,0.722684
6,2017,3.709919e+06,23381.622003,344992.912682,42150,685472.464806,20367.095698,364216.435568,486.037496,5.190986e+06,0.008120,0.004504,0.066460,0.714685,0.132051,0.003924,0.070163,0.714685
7,2018,3.729610e+06,23296.768568,368430.102665,42150,722415.333641,19642.578370,387054.688208,519.783858,5.293119e+06,0.007963,0.004401,0.069605,0.704615,0.136482,0.003711,0.073124,0.704615
8,2019,3.765896e+06,22846.373475,361844.289415,42150,754449.995048,20058.485073,380211.422917,546.569597,5.348003e+06,0.007881,0.004272,0.067660,0.704169,0.141071,0.003751,0.071094,0.704169
9,2020,3.225114e+06,21617.631727,305419.503455,42150,304493.678823,10781.491069,318035.567579,411.191959,4.228023e+06,0.009969,0.005113,0.072237,0.762795,0.072018,0.002550,0.075221,0.762795
10,2021,3.471174e+06,23658.519408,345697.344871,42150,573403.814883,8445.775428,354446.028005,268.017949,4.819243e+06,0.008746,0.004909,0.071733,0.720274,0.118982,0.001753,0.073548,0.720274

In [32]:
# The similarity of the obtained fractions with the information in https://www.bts.gov/sites/bts.dot.gov/files/states2020/Louisiana.pdf
# in the 'HOW RESIDENTS GET TO WORK' graph allow us to believe that the fractions of passenger per Km (private and pblic) is similar to the National numbers. 

years_proj = range(max(years_hist)+1,2050+1)


for var in frac_trns_pkm_dem_private_and_public_vars:
    
    df_historical = df_Passenger_Miles_USA_clean[['Year',var]].copy()
    df_historical['iso_code3'] = 'LA'
    df_historical['Region'] = 'louisiana'
    df_historical.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/historical/'+var+'.csv')

    # Projected value will be tha same as the last historical value

    year_val = []
    
    for year in years_proj:

        val = df_historical.loc[df_historical['Year']==max(years_hist)][var].values[0]

        year_val.append(['LA','louisiana',year,val])
        
    df_projected_out = pd.DataFrame(year_val, columns=['iso_code3','Region', 'Year',var])

    df_projected_out.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/projected/'+var+'.csv')
    
    print('Ready: ', var)

Ready:  frac_trns_pkm_dem_private_and_public_human_powered
Ready:  frac_trns_pkm_dem_private_and_public_powered_bikes
Ready:  frac_trns_pkm_dem_private_and_public_public
Ready:  frac_trns_pkm_dem_private_and_public_road_light

In [33]:
# Regional fractions will be taken a as the national fractions

years_proj = range(max(years_hist)+1,2050+1)


for var in frac_trns_pkm_dem_regional_vars:
    
    df_historical = df_Passenger_Miles_USA_clean[['Year',var]].copy()
    df_historical['iso_code3'] = 'LA'
    df_historical['Region'] = 'louisiana'
    df_historical.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/historical/'+var+'.csv')

    # Projected value will be tha same as the last historical value

    year_val = []
    
    for year in years_proj:

        val = df_historical.loc[df_historical['Year']==max(years_hist)][var].values[0]

        year_val.append(['LA','louisiana',year,val])
        
    df_projected_out = pd.DataFrame(year_val, columns=['iso_code3','Region', 'Year',var])

    df_projected_out.to_csv(grandparentdir+'/'+var+'/input_to_sisepuede/projected/'+var+'.csv')
    
    print('Ready: ', var)

Ready:  frac_trns_pkm_dem_regional_aviation
Ready:  frac_trns_pkm_dem_regional_rail_passenger
Ready:  frac_trns_pkm_dem_regional_road_heavy_regional
Ready:  frac_trns_pkm_dem_regional_road_light