In [1]:
#Add parent and grandparent folder to sys.path and get variable name
import os
import sys
import inspect

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)

# var_name=os.path.basename(parentdir)

# var_name

In [3]:
import pandas as pd
import numpy as np
import os

# set the directory path and the prefix string
directory = grandparentdir
prefix = 'frac_trns_mtkm_dem_freight'

frac_mtkm=[]
# iterate over all items in the directory
for item in os.listdir(directory):
    # check if the item is a directory and starts with the prefix
    if os.path.isdir(os.path.join(directory, item)) and item.startswith(prefix):
        frac_mtkm.append(item)
        # print the directory name
        print(item)
frac_mtkm

frac_trns_mtkm_dem_freight_water_borne
frac_trns_mtkm_dem_freight_road_heavy_freight
frac_trns_mtkm_dem_freight_rail_freight
frac_trns_mtkm_dem_freight_aviation

['frac_trns_mtkm_dem_freight_water_borne',
 'frac_trns_mtkm_dem_freight_road_heavy_freight',
 'frac_trns_mtkm_dem_freight_rail_freight',
 'frac_trns_mtkm_dem_freight_aviation']

In [28]:
## Regional data is the national value
# Obtained from https://data.oecd.org/transport/freight-transport.htm#indicator-chart (last visited 01/June/2024)
df_freight=pd.read_csv("../row_data/DP_LIVE_18012023235438219.csv")
# df_freight=pd.read_csv("../row_data/imputated_freight_data.csv")
df_aviation=pd.read_csv("../row_data/Aviation_freigth_inputed.csv",index_col=0)

df_freight=df_freight.fillna(0)
df_freight

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,FREIGHTTRANSP,RAIL,MLN_TONNEKM,A,1970,36006.000000,0
1,AUS,FREIGHTTRANSP,RAIL,MLN_TONNEKM,A,1971,39704.000000,0
2,AUS,FREIGHTTRANSP,RAIL,MLN_TONNEKM,A,1972,42661.000000,0
3,AUS,FREIGHTTRANSP,RAIL,MLN_TONNEKM,A,1973,46711.000000,0
4,AUS,FREIGHTTRANSP,RAIL,MLN_TONNEKM,A,1974,54075.000000,0
...,...,...,...,...,...,...,...,...
8520,UZB,FREIGHTTRANSP,ROAD,MLN_TONNEKM,A,2016,13297.762249,0
8521,UZB,FREIGHTTRANSP,ROAD,MLN_TONNEKM,A,2017,13607.724500,0
8522,UZB,FREIGHTTRANSP,ROAD,MLN_TONNEKM,A,2018,14640.837100,0
8523,UZB,FREIGHTTRANSP,ROAD,MLN_TONNEKM,A,2019,15879.300000,0
8524,UZB,FREIGHTTRANSP,ROAD,MLN_TONNEKM,A,2020,16233.417045,0

In [29]:
df_aviation_USA = df_aviation[df_aviation['iso_code3']=='USA']

df_aviation_USA

             Nation iso_code3  Year  Aviation (mtkm)
1710  United States       USA  2011     39621.913535
1711  United States       USA  2012     39111.340378
1712  United States       USA  2013     37113.558922
1713  United States       USA  2014     38225.196089
1714  United States       USA  2015     37866.224512
1715  United States       USA  2016     38657.919041
1716  United States       USA  2017     41591.551767
1717  United States       USA  2018     42985.299596
1718  United States       USA  2019     42498.262662
1719  United States       USA  2020     40793.094662

In [7]:
df_freight_USA = df_freight[df_freight['LOCATION']=='USA']
df_freight_USA

,SUBJECT,LOCATION,TIME,Value,INDICATOR,MEASURE,FREQUENCY
656,COAST,USA,2021,2.156948e+06,FREIGHTTRANSP,MLN_TONNEKM,A
986,COAST,USA,2012,2.293490e+05,FREIGHTTRANSP,MLN_TONNEKM,A
994,COAST,USA,2014,2.518010e+05,FREIGHTTRANSP,MLN_TONNEKM,A
1001,COAST,USA,2015,2.563762e+05,FREIGHTTRANSP,MLN_TONNEKM,A
1021,COAST,USA,2020,2.030200e+06,FREIGHTTRANSP,MLN_TONNEKM,A
1235,COAST,USA,2013,2.391580e+05,FREIGHTTRANSP,MLN_TONNEKM,A
1371,COAST,USA,2017,2.569550e+05,FREIGHTTRANSP,MLN_TONNEKM,A
1375,COAST,USA,2018,2.534510e+05,FREIGHTTRANSP,MLN_TONNEKM,A
1491,COAST,USA,2016,2.506899e+05,FREIGHTTRANSP,MLN_TONNEKM,A
1704,COAST,USA,2019,2.032135e+06,FREIGHTTRANSP,MLN_TONNEKM,A
1711,COAST,USA,2011,2.631050e+05,FREIGHTTRANSP,MLN_TONNEKM,A
2319,INLAND,USA,2011,6.271579e+06,FREIGHTTRANSP,MLN_TONNEKM,A
2330,INLAND,USA,2014,6.813036e+06,FREIGHTTRANSP,MLN_TONNEKM,A
2339,INLAND,USA,2016,6.549375e+06,FREIGHTTRANSP,MLN_TONNEKM,A
2357,INLAND,USA,2021,7.961300e+06,FREIGHTTRANSP,MLN_TONNEKM,A
2711,INLAND,USA,2018,7.464561e+06,FREIGHTTRANSP,MLN_TONNEKM,A
2717,INLAND,USA,2020,7.873861e+06,FREIGHTTRANSP,MLN_TONNEKM,A
2936,INLAND,USA,2013,6.644027e+06,FREIGHTTRANSP,MLN_TONNEKM,A
2942,INLAND,USA,2015,6.686902e+06,FREIGHTTRANSP,MLN_TONNEKM,A
3072,INLAND,USA,2017,6.659498e+06,FREIGHTTRANSP,MLN_TONNEKM,A
3244,INLAND,USA,2019,7.699321e+06,FREIGHTTRANSP,MLN_TONNEKM,A
3294,INLAND,USA,2012,6.392695e+06,FREIGHTTRANSP,MLN_TONNEKM,A
3656,RAIL,USA,2012,2.500300e+06,FREIGHTTRANSP,MLN_TONNEKM,A
3661,RAIL,USA,2013,2.541355e+06,FREIGHTTRANSP,MLN_TONNEKM,A
3666,RAIL,USA,2015,2.537845e+06,FREIGHTTRANSP,MLN_TONNEKM,A
3675,RAIL,USA,2017,2.449731e+06,FREIGHTTRANSP,MLN_TONNEKM,A
4381,RAIL,USA,2011,2.524667e+06,FREIGHTTRANSP,MLN_TONNEKM,A
4408,RAIL,USA,2018,2.523408e+06,FREIGHTTRANSP,MLN_TONNEKM,A
4758,RAIL,USA,2014,2.702743e+06,FREIGHTTRANSP,MLN_TONNEKM,A
4777,RAIL,USA,2019,2.364144e+06,FREIGHTTRANSP,MLN_TONNEKM,A
5026,RAIL,USA,2020,2.105254e+06,FREIGHTTRANSP,MLN_TONNEKM,A
5030,RAIL,USA,2021,3.307320e+06,FREIGHTTRANSP,MLN_TONNEKM,A
5131,RAIL,USA,2016,2.314699e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6689,ROAD,USA,2011,2.379954e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6695,ROAD,USA,2012,2.660295e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6697,ROAD,USA,2013,2.926454e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6702,ROAD,USA,2014,2.856882e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6707,ROAD,USA,2015,2.899252e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6710,ROAD,USA,2016,3.008681e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6715,ROAD,USA,2017,2.952877e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6718,ROAD,USA,2018,3.022801e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6722,ROAD,USA,2019,3.238764e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6725,ROAD,USA,2020,3.308665e+06,FREIGHTTRANSP,MLN_TONNEKM,A
6730,ROAD,USA,2021,3.349233e+06,FREIGHTTRANSP,MLN_TONNEKM,A

In [25]:
# historical data

years_hist = range(2011,2020+1)
df_freight_USA_hist = pd.DataFrame(years_hist,columns=['Year'])

df_freight_USA_hist ['RAIL'] = df_freight_USA[(df_freight_USA['TIME']>= 2010) & 
                        (df_freight_USA['TIME']<= 2020) &
                        (df_freight_USA['SUBJECT']== 'RAIL')]['Value'].values

df_freight_USA_hist ['ROAD'] = df_freight_USA[(df_freight_USA['TIME']>= 2010) & 
                        (df_freight_USA['TIME']<= 2020) &
                        (df_freight_USA['SUBJECT']== 'ROAD')]['Value'].values

df_freight_USA_hist ['INLAND'] = df_freight_USA[(df_freight_USA['TIME']>= 2010) & 
                        (df_freight_USA['TIME']<= 2020) &
                        (df_freight_USA['SUBJECT']== 'INLAND')]['Value'].values

df_freight_USA_hist ['COAST'] = df_freight_USA[(df_freight_USA['TIME']>= 2010) & 
                        (df_freight_USA['TIME']<= 2020) &
                        (df_freight_USA['SUBJECT']== 'COAST')]['Value'].values

df_freight_USA_hist ['Aviation'] = df_aviation_USA['Aviation (mtkm)'].values

df_freight_USA_hist ['Total_MTKm'] = df_freight_USA_hist ['COAST'] + df_freight_USA_hist['RAIL'] + df_freight_USA_hist['ROAD'] + df_freight_USA_hist['INLAND'] + df_freight_USA_hist ['Aviation']

df_freight_USA_hist ['frac_trns_mtkm_dem_freight_water_borne'] = df_freight_USA_hist ['COAST']/df_freight_USA_hist ['Total_MTKm']
df_freight_USA_hist ['frac_trns_mtkm_dem_freight_road_heavy_freight'] = (df_freight_USA_hist ['ROAD']+df_freight_USA_hist ['INLAND'])/df_freight_USA_hist ['Total_MTKm']
df_freight_USA_hist ['frac_trns_mtkm_dem_freight_rail_freight'] = df_freight_USA_hist ['RAIL']/df_freight_USA_hist ['Total_MTKm']
df_freight_USA_hist ['frac_trns_mtkm_dem_freight_aviation'] = df_freight_USA_hist ['Aviation']/df_freight_USA_hist ['Total_MTKm']

df_freight_USA_hist['iso_code3'] = 'LA'
df_freight_USA_hist['Region'] = 'louisiana'

df_freight_USA_hist

,Year,RAIL,ROAD,INLAND,COAST,Aviation,Total_MTKm,frac_trns_mtkm_dem_freight_water_borne,frac_trns_mtkm_dem_freight_road_heavy_freight,frac_trns_mtkm_dem_freight_rail_freight,frac_trns_mtkm_dem_freight_aviation,iso_code3,Region
0,2011,2500300.0,2379954.000,6271579.000,2.293490e+05,39621.913535,1.142080e+07,0.020082,0.757524,0.218925,0.003469,LA,louisiana
1,2012,2541355.0,2660295.000,6813036.400,2.518010e+05,39111.340378,1.230560e+07,0.020462,0.769839,0.206520,0.003178,LA,louisiana
2,2013,2537845.0,2926454.000,6549374.800,2.563762e+05,37113.558922,1.230716e+07,0.020831,0.769944,0.206209,0.003016,LA,louisiana
3,2014,2449731.0,2856882.000,7464560.941,2.030200e+06,38225.196089,1.483960e+07,0.136810,0.695534,0.165081,0.002576,LA,louisiana
4,2015,2524667.0,2899252.000,7873861.233,2.391580e+05,37866.224512,1.357480e+07,0.017618,0.793611,0.185982,0.002789,LA,louisiana
5,2016,2523408.0,3008681.000,6644027.400,2.569550e+05,38657.919041,1.247173e+07,0.020603,0.773967,0.202330,0.003100,LA,louisiana
6,2017,2702743.0,2952877.000,6686902.200,2.534510e+05,41591.551767,1.263756e+07,0.020055,0.762788,0.213866,0.003291,LA,louisiana
7,2018,2364144.0,3022801.000,6659498.000,2.506899e+05,42985.299596,1.234012e+07,0.020315,0.784620,0.191582,0.003483,LA,louisiana
8,2019,2105254.0,3238764.201,7699321.139,2.032135e+06,42498.262662,1.511797e+07,0.134419,0.723515,0.139255,0.002811,LA,louisiana
9,2020,2314699.0,3308665.428,6392694.600,2.631050e+05,40793.094662,1.231996e+07,0.021356,0.787451,0.187882,0.003311,LA,louisiana

In [27]:
years_proj = range(max(years_hist)+1,2050+1)

for var_name in frac_mtkm:
    df_historical = df_freight_USA_hist[['Region','iso_code3','Year',var_name]]
    years_proj = range(max(years_hist)+1,2050+1)
    df_projected = pd.DataFrame(years_proj,columns=['Year'])
    df_projected['iso_code3'] = 'LA'
    df_projected['Region'] = 'louisiana'
    df_projected[var_name] = df_historical[df_historical['Year']==max(years_hist)][var_name].values[0]
    # Write data
    df_historical.to_csv(grandparentdir+'/'+var_name+'/input_to_sisepuede/historical/'+var_name+'.csv')
    df_projected.to_csv(grandparentdir+'/'+var_name+'/input_to_sisepuede/projected/'+var_name+'.csv')